### ISSUE TITLE
Error building on ubuntu 18.4

### ISSUE THREAD

**Issue by EliasTsegaw** [opencog/docker#146]
Error at step 33

[docker build progress.txt](https://github.com/opencog/docker/files/4080380/docker.build.progress.txt)

**Comment by AmeBel** [comment]
The ros imagges haven't been maintained in a while. Use https://github.com/opencog/docker/blob/master/opencog/docker-build.sh

**Comment by linas** [comment]
Elias, actually, the first errors is in step 1: it's using 14.04 not 18.04  

but then step 9 is wrong, cause its not trusty any more.  its 18.04

then step 11 is wrong, because indigo is 5 years old, you have to use kinetic or melodic

step 33 crashes because the compiler is too old. 

You have to start at the beginning, and modernize everything.

**Comment by linas** [comment]
@AmeBel  Elias wants to revive the old Eva code, and to do that, he will have to modernize a lot of infrastructure. So starting in the middle with your build script might be challenging ... it might be easiest for him to learn about docker, from the very beginning. 

So Elias, my advice would be to create a new directory called "melodic" (because of this: http://wiki.ros.org/Distributions ) and copy the files from indigo to this new directory, and start altering them: first, changing 14.04 to 18.04 and changing trusty to bionic, and so on, modernizing everything in the scripts.

**Comment by AmeBel** [comment]
stail
