### ISSUE TITLE
Error building noetic/ros-opencog docker image

### ISSUE THREAD

**Issue by Mforrest20** [opencog/docker#174]
This is in the same vain of #173. I can't seem to get ros-opencog to build and I'm not sure how to proceed to do so. I'll post the error below and hopefully redirect the effort @linas would have put towards #173 into this issue.

As before building the ros-base image produces no errors. However building ros-opencog image appears to fail at the point of compiling matrix.scm. This is with leaving the current date (2022-03-05) as is for the opencog source, but rolling it back does not change anything in this case.

Thanks again for any help that is provided with this.

```
[100%] Built target opencog_exec_go
[100%] Built target opencog_persist-file_go
[100%] Built target opencog_uuid_go
wrote `/opencog/atomspace/build/opencog/scm/opencog/query.go'
[100%] Built target opencog_query_go
wrote `/opencog/atomspace/build/opencog/scm/opencog/test-runner.go'
[100%] Built target opencog_test-runner_go
ice-9/boot-9.scm:752:25: In procedure dispatch-exception:
Syntax error:
opencog/matrix/group-similarity.scm:112:16: definition in expression context, where definitions are not allowed, in form (define list-of-all-co-idx (insert-into-set-of-all-co-idx #f))
make[2]: *** [opencog/matrix/CMakeFiles/matrix_go.dir/build.make:84: opencog/scm/matrix.go] Error 1
make[1]: *** [CMakeFiles/Makefile2:3726: opencog/matrix/CMakeFiles/matrix_go.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
wrote `/opencog/atomspace/build/opencog/scm/opencog/logger.go'
[100%] Built target opencog_logger_go
wrote `/opencog/atomspace/build/opencog/scm/opencog/persist.go'
[100%] Built target opencog_persist_go
wrote `/opencog/atomspace/build/opencog/scm/sheaf.go'
[100%] Built target sheaf_go
make: *** [Makefile:152: all] Error 2
[  0%] Built target SCM_CONFIG
[  0%] Built target opencog_atom_types
[  0%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_atoms_atom_types
[  0%] Built target atom_types
[  5%] Built target value
[  8%] Built target truthvalue
[ 11%] Built target atombase
[ 29%] Built target atomcore
[ 32%] Built target atomflow
[ 32%] Built target parallel
[ 38%] Built target clearbox
[ 38%] Built target execution
[ 38%] Built target foreign
[ 41%] Built target grounded
[ 41%] Built target join
[ 44%] Built target query-engine
[ 50%] Built target pattern
[ 50%] Built target atomspace
[ 52%] Built target storage_types
[ 52%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_persist_storage
[ 52%] Built target storage-types
[ 58%] Built target smob
[ 61%] Built target persist
[ 64%] Built target sexpr
[ 64%] Built target load_scm
[ 64%] Built target persist-file
[ 67%] Built target json
[ 67%] Built target tlb
[ 67%] Built target exec
[ 70%] Built target guile-uuid
[ 73%] Built target type-utils
[ 73%] Built target randgen
[ 73%] Built target logger
[ 73%] Built target COPY_TO_LOAD_PATH_IN_BUILD_DIR_FROM__opencog_atomspace_opencog_scm
[ 76%] Built target opencog_go
[ 76%] Built target opencog_type-utils_go
[ 76%] Built target opencog_randgen_go
[ 76%] Built target opencog_query_go
[ 76%] Built target opencog_persist-file_go
[ 76%] Built target opencog_extension_go
[ 79%] Built target executioncontext
[ 79%] Built target py_atomspace_header
[ 79%] Built target PythonEval
[ 82%] Built target PythonSCM
[ 82%] Built target opencog_python_go
[ 85%] Built target opencog_test-runner_go
[ 85%] Built target opencog_exec_go
[ 85%] Built target opencog_uuid_go
[ 85%] Built target opencog_logger_go
[ 85%] Built target opencog_persist_go
[ 85%] Compiling matrix.scm
ice-9/boot-9.scm:752:25: In procedure dispatch-exception:
Syntax error:
opencog/matrix/group-similarity.scm:112:16: definition in expression context, where definitions are not allowed, in form (define list-of-all-co-idx (insert-into-set-of-all-co-idx #f))
make[2]: *** [opencog/matrix/CMakeFiles/matrix_go.dir/build.make:84: opencog/scm/matrix.go] Error 1
make[1]: *** [CMakeFiles/Makefile2:3726: opencog/matrix/CMakeFiles/matrix_go.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
The command '/bin/sh -c (mkdir /opencog/atomspace/build; cd /opencog/atomspace/build; 	cmake ..; make -j12; make install)' returned a non-zero code: 2
```

**Comment by mwigzell** [comment]
Hey Matt, what I was trying to say earlier was predicated on the assumption
you wanted to build latest opencog. But I saw you mention you were checking
it out for a certain date. Well, I have no idea about that, but you'd have
to get all the tools back to that date, that will be difficult. I wouldn't.

If your goal is to get Eva working well, with the old code you would be
able to bring up the Eva image in Blender by hand, but the code was broken,
the WebCam stuff was broken. so the whole thing wouldn't work I don't
believe. At any rate, the last working Eva was with Blender 2.79b, which is
dated to that time. It won't work in a docker configuration using modern
docker. There are issues with X11 rendering.
The way I left the code in "noetic" as I recall, it is using the latest
Blender. Things come up but the latest Blender cannot run the Evan file
(Sophia.blend) because after 2.79b the Blender Rendering engine was
switched out. Read the thread I copied you on. However the new Blender does
run in the latest Docker.

All we need is to get that "Sophia.blend" file fixed. But I have not found
anyone capable of fixing it I'm afraid.

--Mark

**Comment by Mforrest20** [comment]
Hi Mark, I took the time to fully read through that conversation and it looks like you guys were making significant progress, but the conversation came to a halt. At the end of the day I'm determined to get Eva running again with OpenCog to make her interactive. I want to tackle this on two fronts: 1) Eliciting help towards getting the blender files fixed and bringing Eva into this decade AND 2) Putting in effort to make the old code work. Additionally I'm going to request Linas create a channel to organize and aid these efforts.

1) There has been another user (textametron) posting in the [Discord](https://discord.gg/vxPc6sz) with regards to blender and OpenCog and I'd like to bring them into this conversation. They may have the insight we need to move forward, or they may know some people who are willing to help us get it solved.

2) This conversation is happening within the opencog/docker repo, but I think it would be best to start with getting Indigo Eva running on my system, then putting in the work to containerize it. You've mentioned this is not possible but I would still like to give it a try. Questions that will need to be resolved are:

1. Have you tried doing this outside the docker images?
2. You mention the code was broken but is that for attempting to run on the new version of blender?
3. Are the issues you mention with the X11 rendering due to networking within docker? ([If so I believe it is possible to resolve those with effort](https://stackoverflow.com/questions/48235040/run-x-application-in-a-docker-container-reliably-on-a-server-connected-via-ssh-w))
4. Outside sourcing the old dependencies/tool dated to that era, are there any other problems I'm glossing over?

Thank you again for your help with this.

**Comment by mwigzell** [comment]
Hi Matt, I gave up on indigo because I was trying to use the current
version of all repos with a relatively current version of Ubuntu etc.
By trying to do that I realized I needed to use the "noetic" ROS in order
to be current. (not to mention updates to Java and Python.)
If you want to try and re-create an exact replica of some old version,
well, yes you'll have to get a matching timestamp from opencog repos, but
also from the perception/camera stuff too. I really don't see the point in
that: but you may want to do it.

   1. Great if we can get more people, super!
   2. Like I say ...



   1. Yes, I tried doing this with Lnux Containers, completely outside
   docker. After I succeeded in building the noetic based code, I then moved
   it back into the docker. (noetic folder)
   2. The break comes between Blender 2.79b and the next version which I
   guess is Blender 2.80. Blender breaks us, because they withdrew support for
   the native Blender rendering engine and switched to something else.
   3. The issues were between current Docker and Blender of time gone by.
   The newer Docker doesn't support old Blender. The new Docker and new
   Blender work together. But of course the new Blender doesn't work with the
   old blend file.
   4. I wanted to do something like this, so I could at least see how the
   old code worked. Maybe work on the original ROS perception etc. with a
   working Blender etc. I thought, at least I can have the satisfaction of
   working with the functioning code. I think it would be difficult to find
   which version of the camera/perception code to work with. The trouble is
   that the original code worked with a robot, and the modified code worked
   with a sub-set of that, the part that would map to the ROS blender node. I
   got the impression that because different people were working on different
   aspects, for their own sub-goals, no-one was making sure that everything
   that was committed to the repos actually worked together. I ran into
   blatant errors, due to mismatch of code. I found the Python part to be
   exceedingly misleading, but you may be a Python expert. I am not. I was
   unwilling to use old Docker, I use ARCH linux, I was unwilling to create an
   Ubuntu partition on my computer. In the end, the way to commit your changes
   and share them has to be over docker if you want to renovate Eva and share
   it. And then? you can't share an anachronism can you? you MUST update it.
   (the Eva blender support). That is the crux. If we can get the a new
   version of the current blend file to work with the new Blender, by doing
   the work I was trying to organize, i.e. convert the 2.79b blend file using
   the appropriate version of Blender, into a blend file that renders with the
   new rendering engine, and not destroying the armature and the python API
   ROS node in the process, then that is the actual hard part that caused me
   to pause work here. If we can get that going, I too am willing to get back
   into it. BTW: maybe I am not being clear: in order to solve the Eva render
   issue you don't need to build all those docker folders: Just download the
   current  blender_api and install the Blender 2.79b on your system. Then run
   the Blender as I was explaining in those conversations you mention. You
   should be able to replicate what I was doing, which is, to run the 2.79b
   Blender with the the python api.

Did you see this:
https://github.com/opencog/blender_api/blob/master/README_PROGRESS.md ?
It shows this movie:
https://04735475913824401098.googlegroups.com/attach/19054d7814f89/simplescreenrecorder-2022-03-06_10.45.45.mp4?part=0.1&view=1&vt=ANaJVrHp7cB65GdhAIvHyJNuldjPyrEOXJSyx8ksj_Dwg2sxwaZsgqZ09iy8iXt32hsHLb6jaYIejMR00_3ofGsxHs0Bwyu0Ck-jjh9gTzuJHmle7nIBV6o



Once we get the Blender file issue solved, I believe the noetic folder is
ready to go with the (almost) latest stuff from opencog. I don't see the
build issue you ran into as much of a problem: that is just current opencog
fluctuations, the parts we care about aren't being touched. Once that
initial set of docker folders in "noetic" have been made to work, we can
port over the interesting other folders. There is one folder that "does it
all" that needs porting, but it relies on the existing "noetic" folders
working properly at run time, something I haven't seen yet. The
"perception" folder needs work, as soon as we get the Eva ROS node up and
responding to the gesture commands etc., we can work with
@***@***.*** ***@***.***> to build in a working
"atomspace" connectivity, that will be exciting. It would enable LOTS of
people to start creating quasi-sentience, as long as it utilizes the
atomspace to represent itself...

Cheers!

--Mark

**Comment by mwigzell** [comment]
Hey Matt, I re-ran my containers without touch the date which was around
Feb 5, 2022.
But when I did a full rebuild, first of noetic/ros-base then of
noetic/ros-opencog I basically duplicated the issue you mention:

> [ 85%] Compiling matrix.scm
> ice-9/boot-9.scm:752:25: In procedure dispatch-exception:
> Syntax error:
> opencog/matrix/group-similarity.scm:112:16: definition in expression
> context, where definitions are not allowed, in form (define
> list-of-all-co-idx (insert-into-set-of-all-co-idx #f))
> make[2]: *** [opencog/matrix/CMakeFiles/matrix_go.dir/build.make:84:
> opencog/scm/matrix.go] Error 1
> make[1]: *** [CMakeFiles/Makefile2:3729:
> opencog/matrix/CMakeFiles/matrix_go.dir/all] Error 2
> make: *** [Makefile:152: all] Error 2
> The command '/bin/sh -c (mkdir /opencog/atomspace/build; cd
> /opencog/atomspace/build; cmake ..; make -j12; make install)' returned a
> non-zero code: 2
>

Since I don't maintain that repo, I'll ask @***@***.***
***@***.***>

**Comment by mwigzell** [comment]
Hi Matt, one more thing: you don't need to build "ros-opencog" yet, since
"eva-ros" is not running properly yet: there is no point in trying, till
everything works at the "eva-ros" level.
Regards,
--Mark

**Comment by Mforrest20** [comment]
Hey Mark, thanks for that update. I also failed to mention (though maybe implied) I'm abandoning the attempt to re-implement the old version. You provided a convincing argument against doing so. (Chiefly getting the perception/camera files and other non-open source/non-published packages dated to the precise time things were working). The fact that significant work is being made to get things working with the new system makes spending effort there appear to be a lost cause.

Re the error: Although it is not convenient for this to be broken for either of us, it is good to hear it there is consistency to the issue. As well as there being justification for this issue to remain open.

**Comment by mwigzell** [comment]
Hi Matt, yes, I don't think we even need to reconstitute the original
working solution to get this working. What we need is a solution for the
Blender / blend file problem. That can be tackled directly manually as
outlined in those threads.
The "eva-ros", "ros-blender" and "ros-base" dockers from the "noetic"
folder are what we need, and they do work, at least last time I tried. The
issue is the Blender / blend file problem.

Re the error: Although it is not convenient for this to be broken for
> either of us, it is good to hear it there is consistency to the issue. As
> well as there being justification for this issue to remain open.
>
So yes, I have asked @linas about this, waiting for a reply. However it
doesn't impact us for the foreseeable future: We only need "ros-opencog"
when "eva-ros" works flawlessly.at run time. That will be a great day.
Regards,
--Mark

**Comment by mwigzell** [comment]
Hey Matt, I didn't say I don't have the problem you describe in the title:
I just saw it as immaterial to the effort: its just a syntax error in
opencog libs somewhere which can happen, they will get to it I think. Let
me try a run through to see if I have same issue. I'll get back to you.

**Comment by mwigzell** [comment]
Hi Matt, without trying this myself, just on the error message above, it
would appear that opencog atm is not building. There is a clear compiler
syntax error:

opencog/matrix/group-similarity.scm:112:16: definition in expression
context, where definitions are not allowed, in form (define
list-of-all-co-idx (insert-into-set-of-all-co-idx #f))
make[2]: *** [opencog/matrix/CMakeFiles/matrix_go.dir/build.make:84:
opencog/scm/matrix.go] Error 1

**Comment by linas** [comment]
Closing, I think this is all now resolved. I did a bunch of updates for #182 and it builds cleanly, now.
